baseURL: https://adamijak.github.io/
languageCode: en-us
title: My Blog
theme: PaperMod

params:

menu:
  main:
    - identifier: pages
      name: pages
      url: /pages/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20
